name: 'Synopsys Detect'
description: 'Add SAST and SCA scanning to your GitHub repositories with Synopsys Coverity on Polaris and Black Duck.'
author: 'Gautam Baghel @ Synopsys'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  args:
    description: 'Synopsys Detect arguments'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
